name: node.js Package
on:
  push:
    branches:
      - main
jobs:
  deletepgk:
    runs-on: ubuntu-latest
    steps:  
      - uses: actions/delete-package-versions@v3
        with:
          owner: 'ArmenNaga'
          repo: 'ArmenNaga/github-actions-package'
          package-name: '@armennag/test-package'
          token: ${{ secrets.REPOSECRET }}
          min-versions-to-keep: 2
      

    
