name: node.js Package
on:
  push:
    branches:
      - main
jobs:
  publish-gpr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version : 16
          registry-url: https://npm.pkg.github.com/
          scope: '@armennag'
      - run: npm install
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
  deletepgk:
    runs-on: ubuntu-latest
    needs: publish-gpr 
    steps:

    - uses: actions/delete-package-versions@v3
    #- uses: actions/delete-package-versions-keep-latest@v3
      with:
        owner: 'armennag'
        repo: 'github-actions-package'
        package-name: '1.0.0-alpha'
        token: ${{ secrets.reposecret }}
        keep-latest-package-versions: 20
        delete-only-pre-release-versions: "false"
        ignore-versions: '^(0|[1-9]\\d*)\\.0\\.0$'
      

    
