name: node.js Package
on:
  push:
    branches:
      - main
jobs:
  publish-gpr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version : 16
          registry-url: https://npm.pkg.github.com/
          scope: '@armennag'
      - run: npm install
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
  deletepgk:
    runs-on: ubuntu-latest
    steps:  
      - uses: actions/delete-package-versions@v3
        with:
          owner: 'armennag'
          repo: 'github-actions-package'
          package-name: 'test-package'
          token: ${{ secrets.REPOSECRET }}
          min-versions-to-keep: 2
      

    
