name: node.js Package
on:
  push:
    branches:
      - main
    
jobs:
  deletepgk:
    runs-on: ubuntu-latest
    steps:  
      - uses: actions/setup-node@v2
        with:
          registry-url: https://npm.pkg.github.com/
      - run : npm install @armennag/github-actions-package@1.0.0
      - uses: actions/delete-package-versions@v3
        with:
          owner: 'ArmenNag'
          package-name: 'test-package'
          num-old-versions-to-delete: 3
          token: ${{ secrets.REPOSECRET }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.REPOSECRET }}
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    
