name: node.js Package
on:
  push:
    branches:
      - main
jobs:
  deletepgk:
    runs-on: ubuntu-latest
    steps:  
      - uses: actions/delete-package-versions@v3
        with:
          package-name: '@armennag/test-package@2.1.3'
          num-old-versions-to-delete: 3
      

    
