name: node.js Package
on:
  push:
    branches:
      - main
    
jobs:
  deletepgk:
    runs-on: ubuntu-latest
    steps:  
      - uses: SmartsquareGmbH/delete-old-packages@v0.5.0
        with:
          keep: 5
          names: |
                '@armennag/nowy@1.0.0'
      

    
